### ISSUE TITLE
Conversion of model fails with assertion in Quantize operator

### ISSUE THREAD

**Issue by deiruch** [jackwish/tflite2onnx#31]
**Describe the bug**
When I try to convert [segm_full_v491.zip](https://github.com/jackwish/tflite2onnx/files/5581862/segm_full_v491.zip) on the command line, I get the following traceback:
```
<class 'tflite2onnx.op.quantize.Quantize'>
Traceback (most recent call last):
  File "/home/de/.local/bin/tflite2onnx", line 8, in <module>
    sys.exit(cmd_convert())
  File "/home/de/.local/lib/python3.8/site-packages/tflite2onnx/convert.py", line 55, in cmd_convert
    convert(args.tflite_path, args.onnx_path)
  File "/home/de/.local/lib/python3.8/site-packages/tflite2onnx/convert.py", line 44, in convert
    model.convert(explicit_layouts)
  File "/home/de/.local/lib/python3.8/site-packages/tflite2onnx/model.py", line 39, in convert
    self.parse()
  File "/home/de/.local/lib/python3.8/site-packages/tflite2onnx/model.py", line 31, in parse
    g.parse()
  File "/home/de/.local/lib/python3.8/site-packages/tflite2onnx/graph.py", line 63, in parse
    op.parse()
  File "/home/de/.local/lib/python3.8/site-packages/tflite2onnx/op/quantize.py", line 33, in parse
    logger.debug("Parsing %s...", self.shorty)
  File "/home/de/.local/lib/python3.8/site-packages/tflite2onnx/op/common.py", line 122, in shorty
    return '[%s](%s)' % (self.name, self.type)
  File "/home/de/.local/lib/python3.8/site-packages/tflite2onnx/op/quantize.py", line 25, in type
    return 'QuantizeLinear' if self.isQuantize else 'DequantizeLinear'
  File "/home/de/.local/lib/python3.8/site-packages/tflite2onnx/op/quantize.py", line 29, in isQuantize
    assert(self.status.parsed)
AssertionError
```

**To Reproduce**
1. Extract the model linked above
1. Execute `tflite2onnx segm_full_v491.tflite segm_full_v491.onnx`

**Additional context**
The model is the background segmentation from Google Meet

**Comment by jackwish** [comment]
Hi @deiruch it seems your model includes data type `float16`. We already have an issue discussing related topic: https://github.com/jackwish/tflite2onnx/issues/30. We have a plan of enabling such cases in next version. I am going to close this issue as duplicate with #30.

For next action of your model, I suggest to remove the float16 nodes from the TFLite model - as all the inputs are float16, maybe we don't need to keep them.

**Comment by jackwish** [comment]
Closing as track this issue in #30

**Comment by deiruch** [comment]
Sorry, didn't realize this had the same underlying cause. Will follow the other issue!

Thanks for your work! Much appreciated!

**Comment by jackwish** [comment]
No worry!
