### ISSUE TITLE
Assertion error in isQuantize subroutine

### ISSUE THREAD

**Issue by briangrifiin** [jackwish/tflite2onnx#33]
**Describe the bug**
Quantize::isQuantize method is called from the very beginning of Quantize::parse method via self.shorty.
Quantize::parse does not set self.status.parsed before jumping to Quantize::isQuantize.
Thus, assertion inside Quantize::isQuantize fails.

**To Reproduce**
Try to convert the following model: https://tfhub.dev/google/lite-model/magenta/arbitrary-image-stylization-v1-256/fp16/prediction/1

Detailed steps to reproduce:
1. git clone https://github.com/jackwish/tflite2onnx
2. cd tflite2onnx
3. python3 -m virtualenv /tmp/onnx-env
4. source /tmp/onnx-env/bin/activate
5. python3 -m pip install -r requirements.txt
6. python3 setup.py install
7. wget https://storage.googleapis.com/tfhub-lite-models/google/lite-model/magenta/arbitrary-image-stylization-v1-256/fp16/prediction/1.tflite
8. tflite2onnx ./1.tflite /tmp/out.onnx

Full log:
```
$ tflite2onnx ./1.tflite /tmp/out.onnx
2020-12-14 20:06:08,918 D [tflite2onnx][convert.py:37] tflite: ./1.tflite
2020-12-14 20:06:08,918 D [tflite2onnx][convert.py:38] onnx: /tmp/out.onnx
2020-12-14 20:06:08,924 D [tflite2onnx][model.py:21] Parsing the Model...
2020-12-14 20:06:08,925 D [tflite2onnx][graph.py:58] Parsing the Graph...
2020-12-14 20:06:08,925 D [tflite2onnx][graph.py:61] Parsing operator: 0
Traceback (most recent call last):
  File "/tmp/onnx-env/bin/tflite2onnx", line 14, in <module>
    load_entry_point('tflite2onnx==0.3.0', 'console_scripts', 'tflite2onnx')()
  File "/tmp/onnx-env/lib64/python3.7/site-packages/tflite2onnx-0.3.0-py3.7.egg/tflite2onnx/convert.py", line 55, in cmd_convert
  File "/tmp/onnx-env/lib64/python3.7/site-packages/tflite2onnx-0.3.0-py3.7.egg/tflite2onnx/convert.py", line 44, in convert
  File "/tmp/onnx-env/lib64/python3.7/site-packages/tflite2onnx-0.3.0-py3.7.egg/tflite2onnx/model.py", line 39, in convert
  File "/tmp/onnx-env/lib64/python3.7/site-packages/tflite2onnx-0.3.0-py3.7.egg/tflite2onnx/model.py", line 31, in parse
  File "/tmp/onnx-env/lib64/python3.7/site-packages/tflite2onnx-0.3.0-py3.7.egg/tflite2onnx/graph.py", line 63, in parse
  File "/tmp/onnx-env/lib64/python3.7/site-packages/tflite2onnx-0.3.0-py3.7.egg/tflite2onnx/op/quantize.py", line 33, in parse
  File "/tmp/onnx-env/lib64/python3.7/site-packages/tflite2onnx-0.3.0-py3.7.egg/tflite2onnx/op/common.py", line 122, in shorty
  File "/tmp/onnx-env/lib64/python3.7/site-packages/tflite2onnx-0.3.0-py3.7.egg/tflite2onnx/op/quantize.py", line 25, in type
  File "/tmp/onnx-env/lib64/python3.7/site-packages/tflite2onnx-0.3.0-py3.7.egg/tflite2onnx/op/quantize.py", line 29, in isQuantize
AssertionError
```

**Additional context**
Possible workaround:
```patch
diff --git a/tflite2onnx/op/quantize.py b/tflite2onnx/op/quantize.py
index ced5559..8c67f6f 100644
--- a/tflite2onnx/op/quantize.py
+++ b/tflite2onnx/op/quantize.py
@@ -26,8 +26,11 @@ class Quantize(Operator):
 
     @property
     def isQuantize(self):
-        assert(self.status.parsed)
-        return self.inputs[0].dtype is TensorProto.FLOAT
+        if self.status.parsed:
+            return self.inputs[0].dtype is TensorProto.FLOAT
+        else:
+            opcode = self.model.OperatorCodes(self.tflite.OpcodeIndex()).BuiltinCode()
+            return opcode is tflite.BuiltinOperator.QUANTIZE
 
     def parse(self):
         logger.debug("Parsing %s...", self.shorty)
```

**Comment by jackwish** [comment]
Hi @briangrifiin thank you for reporting this issue! This was not caught because we have not tested `tflite2onnx` with TFLite models containing Quantize or Dequantize with debug log enabled (the debug log should be why no such issue not reported as I have seen many people using similar models pattern).

The fix looks good for me. If it works for your model, would you like to create a PR? That would be very helpful for people using a similar model pattern. @briangrifiin
