### ISSUE TITLE
AssertionError for DepthMultiplier

### ISSUE THREAD

**Issue by paulgavrikov** [jackwish/tflite2onnx#47]
I am trying to convert [this tflite model](https://github.com/google/mediapipe/raw/master/mediapipe/models/knift_float_1k.tflite)  to ONNX but end up in an AssertionError. I am using python3.8.

```
Traceback (most recent call last):
  File "/home/paulgavrikov/.local/bin/tflite2onnx", line 8, in <module>
    sys.exit(cmd_convert())
  File "/home/paulgavrikov/.local/lib/python3.8/site-packages/tflite2onnx/convert.py", line 55, in cmd_convert
    convert(args.tflite_path, args.onnx_path)
  File "/home/paulgavrikov/.local/lib/python3.8/site-packages/tflite2onnx/convert.py", line 44, in convert
    model.convert(explicit_layouts)
  File "/home/paulgavrikov/.local/lib/python3.8/site-packages/tflite2onnx/model.py", line 39, in convert
    self.parse()
  File "/home/paulgavrikov/.local/lib/python3.8/site-packages/tflite2onnx/model.py", line 31, in parse
    g.parse()
  File "/home/paulgavrikov/.local/lib/python3.8/site-packages/tflite2onnx/graph.py", line 63, in parse
    op.parse()
  File "/home/paulgavrikov/.local/lib/python3.8/site-packages/tflite2onnx/op/conv.py", line 81, in parse
    assert(option.DepthMultiplier() == 1)
AssertionError
```

**Comment by jackwish** [comment]
Hi @paulgavrikov thanks for reporting this issue. Could you help to report it with [the bug template](https://github.com/jackwish/tflite2onnx/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) which can help us to have a basic idea of what's going on?

**Comment by paulgavrikov** [comment]
after an update to the latest release I cannot reproduce this anymore. Running into a new error. Will create a new issue.

**Comment by jackwish** [comment]
Closing

**Comment by paulgavrikov** [comment]
I'd like to reopen this, now that I am able to install from source again. 

**Model:** https://github.com/google/mediapipe/blob/master/mediapipe/models/knift_float_1k.tflite
I should mention at this point that according to the doc this model is only suitable for Android and apparently not for python. I am not sure what this exactly means in terms of the model arch, so if this is indeed a problem with the model itself and not this converter then just close the issue. Also, there is not much I can say about this model as it has been created and trained by Google. You can view it with Netron, tho.

**Code:**
```
import tflite2onnx
import logging


logging.basicConfig(format='%(asctime)s %(levelname).1s [%(name)s][%(filename)s:%(lineno)d] %(message)s', level=logging.DEBUG)
tflite_path = 'knift_float_1k.tflite'
onnx_path = 'knift_float_1k.onnx'
tflite2onnx.convert(tflite_path, onnx_path)
```

**Log:**
```
2021-01-21 09:53:31,818 D [tflite2onnx][convert.py:37] tflite: knift_float_1k.tflite
2021-01-21 09:53:31,818 D [tflite2onnx][convert.py:38] onnx: knift_float_1k.onnx
2021-01-21 09:53:31,818 D [tflite2onnx][model.py:21] Parsing the Model...
2021-01-21 09:53:31,818 D [tflite2onnx][graph.py:59] Parsing the Graph...
2021-01-21 09:53:31,818 D [tflite2onnx][graph.py:62] Parsing operator: 0
2021-01-21 09:53:31,818 D [tflite2onnx][conv.py:46] Parsing Conv...
2021-01-21 09:53:31,818 D [tflite2onnx][tensor.py:103] Parsing rgb_to_grayscale_1...
2021-01-21 09:53:31,818 D [tflite2onnx][tensor.py:103] Parsing siamese_neural_congas_1/feature_extraction/Conv/Conv2D_weights...
2021-01-21 09:53:31,819 D [tflite2onnx][tensor.py:103] Parsing siamese_neural_congas_1/feature_extraction/Conv/Conv2D_bias...
2021-01-21 09:53:31,819 D [tflite2onnx][tensor.py:103] Parsing siamese_neural_congas_1/feature_extraction/Conv/Relu6...
Traceback (most recent call last):
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/convert.py", line 10, in <module>
    tflite2onnx.convert(tflite_path, onnx_path)
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/tflite2onnx/convert.py", line 44, in convert
    model.convert(explicit_layouts)
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/tflite2onnx/model.py", line 39, in convert
    self.parse()
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/tflite2onnx/model.py", line 31, in parse
    g.parse()
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/tflite2onnx/graph.py", line 64, in parse
    op.parse()
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/tflite2onnx/op/conv.py", line 81, in parse
    assert(option.DepthMultiplier() == 1)
AssertionError
```

**Version:** `master` (but also happens on latest pypi release)

**Comment by jackwish** [comment]
Hmmm, we assumed the input channel and output channel are the same for depthwise conv. This seems not to be a depthwise conv semantically, but we can get to understand the arithmetic here. I think I have encountered a similar issue in TVM.

**Comment by JKANG94** [comment]
I also met this problem using the latest pypi release to convert tflite model.  How to solve this problem?

**Comment by jackwish** [comment]
@JKANG94 as mentioned in comment https://github.com/jackwish/tflite2onnx/issues/47#issuecomment-764653389, we need to fix the assumption "the input channel and output channel are the same for depthwise conv". https://github.com/jackwish/tflite2onnx/blob/master/tflite2onnx/op/conv.py#L81

But I don't have the time to investigate this issue. Do you have time a take a look at it?
