### ISSUE TITLE
Installation via build-wheel.sh fails

### ISSUE THREAD

**Issue by paulgavrikov** [jackwish/tflite2onnx#49]
**Describe the bug**
It is not possible to install tflite2onnx via the steps described in the readme.

    Download the source code: git clone https://github.com/jackwish/tflite2onnx.git
    Build the package: ${tflite2onnx}/scripts/build-wheel.sh

**To Reproduce**

```bash
paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:~$ git clone https://github.com/jackwish/tflite2onnx.git
Cloning into 'tflite2onnx'...
remote: Enumerating objects: 168, done.
remote: Counting objects: 100% (168/168), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 2249 (delta 90), reused 90 (delta 39), pack-reused 2081
Receiving objects: 100% (2249/2249), 140.72 MiB | 2.55 MiB/s, done.
Resolving deltas: 100% (1593/1593), done.

paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:~$ tflite2onnx/scripts/build-wheel.sh 
tflite2onnx/scripts/build-wheel.sh: line 10: pip: command not found
  File "/home/paulgavrikov/tflite2onnx/setup.py", line 17
SyntaxError: Non-ASCII character '\xe7' in file /home/paulgavrikov/tflite2onnx/setup.py on line 17, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```

**Version**
Which version are you using? `master`.

**Additional context**
Ubuntu 20.04, python3.8.6

**Comment by jackwish** [comment]
Hi @paulgavrikov it seems the `pip` is not available in your env, could you help to confirm?

```
tflite2onnx/scripts/build-wheel.sh: line 10: pip: command not found
```

**Comment by groncarolo** [comment]
Hello,

On 
```
tito@nostromo:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

tito@nostromo:~$ python --version
Python 3.8.5
```

trying to run build-wheel.sh
```
git clone  https://github.com/jackwish/tflite2onnx.git
tito@nostromo:~/fsl/machine_learning/pytorch2tflite$ tflite2onnx/scripts/build-wheel.sh
Requirement already satisfied: numpy in /home/tito/.local/lib/python3.8/site-packages (1.19.5)
Requirement already satisfied: onnx in /home/tito/.local/lib/python3.8/site-packages (1.7.0)
Requirement already satisfied: tflite in /home/tito/.local/lib/python3.8/site-packages (2.3.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /home/tito/.local/lib/python3.8/site-packages (from onnx) (3.7.4.3)
Requirement already satisfied: six in /home/tito/.local/lib/python3.8/site-packages (from onnx) (1.15.0)
Requirement already satisfied: protobuf in /home/tito/.local/lib/python3.8/site-packages (from onnx) (3.13.0)
Requirement already satisfied: flatbuffers in /home/tito/.local/lib/python3.8/site-packages (from tflite) (1.12)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from protobuf->onnx) (45.2.0)
Traceback (most recent call last):
  File "/home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/setup.py", line 2, in <module>
    import tflite2onnx
  File "/home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/tflite2onnx/__init__.py", line 3, in <module>
    from tflite2onnx.convert import convert
  File "/home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/tflite2onnx/convert.py", line 7, in <module>
    from tflite2onnx.model import Model
  File "/home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/tflite2onnx/model.py", line 7, in <module>
    from tflite2onnx.graph import Graph
  File "/home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/tflite2onnx/graph.py", line 6, in <module>
    from tflite2onnx.tensor import TensorFactory
  File "/home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/tflite2onnx/tensor.py", line 7, in <module>
    from tflite2onnx import mapping
  File "/home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/tflite2onnx/mapping.py", line 35, in <module>
    TensorType.BOOL: 'bool',
```
regards

g.

**Comment by groncarolo** [comment]
For file
```
tflite2onnx/tflite2onnx/mapping.py
```
changing
```
diff --git a/tflite2onnx/mapping.py b/tflite2onnx/mapping.py
index f974cf2..d958480 100644
--- a/tflite2onnx/mapping.py
+++ b/tflite2onnx/mapping.py
@@ -1,6 +1,7 @@
 from onnx import TensorProto
 from tflite import TensorType
 
+from tflite.TensorType import TensorType as TFLiteTensorType
 
 def _inverseDict(d):
     return {v: k for k, v in d.items()}
@@ -32,14 +33,14 @@ DTYPE_ONNX2NAME = {
 DTYPE_NAME2ONNX = _inverseDict(DTYPE_ONNX2NAME)
 
 DTYPE_TFLITE2NAME = {
-    TensorType.BOOL: 'bool',
-    TensorType.FLOAT16: 'float16',
-    TensorType.FLOAT32: 'float32',
-    TensorType.INT16: 'int16',
-    TensorType.INT32: 'int32',
-    TensorType.INT64: 'int64',
-    TensorType.INT8: 'int8',
-    TensorType.UINT8: 'uint8',
+    TFLiteTensorType.BOOL: 'bool',
+    TFLiteTensorType.FLOAT16: 'float16',
+    TFLiteTensorType.FLOAT32: 'float32',
+    TFLiteTensorType.INT16: 'int16',
+    TFLiteTensorType.INT32: 'int32',
+    TFLiteTensorType.INT64: 'int64',
+    TFLiteTensorType.INT8: 'int8',
+    TFLiteTensorType.UINT8: 'uint8',
 }
 
 DTYPE_NAME2TFLITE = _inverseDict(DTYPE_TFLITE2NAME)
```
would solve the issue but is just one of many 

same thing would be in 
```
        modified:   tflite2onnx/op/activation.py
        modified:   tflite2onnx/op/binary.py
        modified:   tflite2onnx/op/reshape.py
        modified:   tflite2onnx/op/transpose.py
```

What are we missing? :)

**Comment by jackwish** [comment]
@groncarolo that's interesting, our build is protected by CI. And I have just rerun it and got passing: https://github.com/jackwish/tflite2onnx/runs/1705823307

We can just use `tflite.TensorType.BOOL` directly if we are installing `tflite` package with https://github.com/jackwish/tflite or pip. Could try that in a clean virtual env?

**Comment by paulgavrikov** [comment]
@jackwish, @groncarolo Same issue I was pointing out in #50. Running into the same issue when installing under Ubuntu 20.04 with py3.8.

@jackwish I was more worried about the line endings issue. Typically a problem when you commit under windows, though there is a git config that takes care of that.

Regarding pip: `python` is `python3` under Ubuntu. Is there maybe a universal way to access the binary? Otherwise you could add a parameter to the script to pass the correct binary. I guess it then also makes sense to change `pip` to `<python bin> -m pip`. What do you think?

**Comment by groncarolo** [comment]
@jackwish thanks a lot! : gonna try

starting from empty env
```
virtualenv test_venv/
source ./test_venv/bin/activate
pip list
Package       Version   
------------- ----------
appdirs       1.4.3     
CacheControl  0.12.6    
certifi       2019.11.28
chardet       3.0.4     
colorama      0.4.3     
contextlib2   0.6.0     
distlib       0.3.0     
distro        1.4.0     
html5lib      1.0.1     
idna          2.8       
ipaddr        2.2.0     
lockfile      0.12.2    
msgpack       0.6.2     
packaging     20.3      
pep517        0.8.2     
pip           20.0.2    
pkg-resources 0.0.0     
progress      1.5       
pyparsing     2.4.6     
pytoml        0.1.21    
requests      2.22.0    
retrying      1.3.3     
setuptools    44.0.0    
six           1.14.0    
urllib3       1.25.8    
webencodings  0.5.1     
wheel         0.34.2    
```
trying again 
```
git status 
HEAD detached at v0.3.1


./tflite2onnx/tools/build-wheel.sh
Collecting numpy
  Using cached numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
Collecting onnx
  Downloading onnx-1.8.0-cp38-cp38-manylinux2010_x86_64.whl (7.7 MB)
     |████████████████████████████████| 7.7 MB 2.9 MB/s 
Collecting tflite
  Using cached tflite-2.3.0-py2.py3-none-any.whl (79 kB)
Collecting typing-extensions>=3.6.2.1
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Requirement already satisfied: six in ./tflite2onnx/test_venv/lib/python3.8/site-packages (from onnx) (1.14.0)
Collecting protobuf
  Downloading protobuf-3.14.0-cp38-cp38-manylinux1_x86_64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 2.2 MB/s 
Collecting flatbuffers
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Installing collected packages: numpy, typing-extensions, protobuf, onnx, flatbuffers, tflite
Successfully installed flatbuffers-1.12 numpy-1.19.5 onnx-1.8.0 protobuf-3.14.0 tflite-2.3.0 typing-extensions-3.7.4.3
running bdist_wheel
running build
installing to /home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/assets/build
running install
running install_egg_info
running egg_info
creating tflite2onnx.egg-info
writing tflite2onnx.egg-info/PKG-INFO
writing dependency_links to tflite2onnx.egg-info/dependency_links.txt
writing entry points to tflite2onnx.egg-info/entry_points.txt
writing top-level names to tflite2onnx.egg-info/top_level.txt
writing manifest file 'tflite2onnx.egg-info/SOURCES.txt'
reading manifest file 'tflite2onnx.egg-info/SOURCES.txt'
writing manifest file 'tflite2onnx.egg-info/SOURCES.txt'
Copying tflite2onnx.egg-info to /home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/assets/build/tflite2onnx-0.3.1.egg-info
running install_scripts
creating /home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/assets/build/tflite2onnx-0.3.1.dist-info/WHEEL
creating '/home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/assets/dist/tflite2onnx-0.3.1-py3-none-any.whl' and adding '/home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/assets/build' to it
adding 'tflite2onnx-0.3.1.dist-info/METADATA'
adding 'tflite2onnx-0.3.1.dist-info/WHEEL'
adding 'tflite2onnx-0.3.1.dist-info/entry_points.txt'
adding 'tflite2onnx-0.3.1.dist-info/top_level.txt'
adding 'tflite2onnx-0.3.1.dist-info/RECORD'
```

installing
```
pip install assets/dist/tflite2
Processing ./assets/dist/tflite2onnx-0.3.1-py3-none-any.whl
Installing collected packages: tflite2onnx
Successfully installed tflite2onnx-0.3.1
```

sounds good :)

````
(test_venv) tito@nostromo:~$ tflite2onnx out/Subband_Depth_firstLayer_tf_quant.tflite Subband_Depth_firstLayer_tf_quant.onnx 
Traceback (most recent call last):
  File "/home/tito/fsl/machine_learning/pytorch2tflite/tflite2onnx/test_venv/bin/tflite2onnx", line 5, in <module>
    from tflite2onnx.convert import cmd_convert
ModuleNotFoundError: No module named 'tflite2onnx.convert'
```

much better but I still have an issue

**Comment by groncarolo** [comment]
I created yet another venv and simply 
```
pip install tflite2onnx 
```
It works 

Thanks for the help

regards

g,

**Comment by jackwish** [comment]
@groncarolo Very glad that a clean env works for you. I have been using a python3 venv, so maybe it doesn't work in some scenarios...

@paulgavrikov Thanks for the clarification, but the new line issue should not be specific to this `tflite2onnx` project, meaning that it should not be a real issue.

For the `python3 -m`, I think that's a very good catch, we should make our scripts more general, would you mind help to fix that?

**Comment by paulgavrikov** [comment]
@jackwish I set up a clean venv (this would also work without `python`) and tried the latest master with the fp16 fixes but run into a new error (`git config core.autocrlf` set to `input` or `false`, can't run otherwise):

```
$ tflite2onnx/scripts/build-wheel.sh 
Requirement already satisfied: numpy in ./venv/lib/python3.8/site-packages (1.19.5)
Requirement already satisfied: onnx in ./venv/lib/python3.8/site-packages (1.8.0)
Requirement already satisfied: tflite in ./venv/lib/python3.8/site-packages (2.3.0)
Requirement already satisfied: six in ./venv/lib/python3.8/site-packages (from onnx) (1.15.0)
Requirement already satisfied: protobuf in ./venv/lib/python3.8/site-packages (from onnx) (3.14.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./venv/lib/python3.8/site-packages (from onnx) (3.7.4.3)
Requirement already satisfied: flatbuffers in ./venv/lib/python3.8/site-packages (from tflite) (1.12)
running bdist_wheel
running build
installing to /media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/tflite2onnx/assets/build
running install
running install_egg_info
running egg_info
writing tflite2onnx.egg-info/PKG-INFO
Traceback (most recent call last):
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/tflite2onnx/setup.py", line 4, in <module>
    setuptools.setup(
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 335, in run
    self.run_command('install')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/lib/python3.8/distutils/command/install.py", line 601, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/setuptools/command/install_egg_info.py", line 34, in run
    self.run_command('egg_info')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 292, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 628, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/usr/lib/python3.8/distutils/dist.py", line 1117, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/setuptools/dist.py", line 140, in write_pkg_file
    write_field('Summary', single_line(self.get_description()))
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/lib/python3.8/site-packages/setuptools/dist.py", line 124, in single_line
    raise ValueError("newlines not allowed")
ValueError: newlines not allowed

```

**Comment by paulgavrikov** [comment]
@jackwish even with my PR I am still running into the same issue as @groncarolo even with clean venv from code and bash
```
$ tflite2onnx
Traceback (most recent call last):
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/bin/tflite2onnx", line 5, in <module>
    from tflite2onnx.convert import cmd_convert
ModuleNotFoundError: No module named 'tflite2onnx'
```

**Comment by jackwish** [comment]
Hmmm... that’s interesting. It would be helpful if you can list the
commands that are used starting from creating the venv. Are you using
windows? If it’s possible to try on Ubuntu to check if it’s a platform
issue?

**Comment by paulgavrikov** [comment]
I am under Ubuntu! Here's my full log:

```
paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ python3 -m venv venv
paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ venv/bin/activate
paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ source venv/bin/activate
(venv) paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ git clone https://github.com/paulgavrikov/tflite2onnx
Cloning into 'tflite2onnx'...
remote: Enumerating objects: 221, done.
remote: Counting objects: 100% (221/221), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 2302 (delta 122), reused 155 (delta 80), pack-reused 2081
Receiving objects: 100% (2302/2302), 140.74 MiB | 5.60 MiB/s, done.
Resolving deltas: 100% (1625/1625), done.
(venv) paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ cd tflite2onnx/
(venv) paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/tflite2onnx$ git pull origin pr-newline-description
From https://github.com/paulgavrikov/tflite2onnx
 * branch            pr-newline-description -> FETCH_HEAD
Already up to date.
(venv) paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/tflite2onnx$ cd ..
(venv) paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ tflite2onnx/
assets/           _config.yml       .git/             .gitignore        README.md         scripts/          setup.py          tflite2onnx/      
codecov.yaml      docs/             .github/          LICENSE           requirements.txt  setup.cfg         tests/            
(venv) paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ tflite2onnx/
assets/           _config.yml       .git/             .gitignore        README.md         scripts/          setup.py          tflite2onnx/      
codecov.yaml      docs/             .github/          LICENSE           requirements.txt  setup.cfg         tests/            
(venv) paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ tflite2onnx/scripts/build-wheel.sh 
Collecting numpy
  Using cached numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
Collecting onnx
  Using cached onnx-1.8.0-cp38-cp38-manylinux2010_x86_64.whl (7.7 MB)
Collecting tflite
  Using cached tflite-2.3.0-py2.py3-none-any.whl (79 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting typing-extensions>=3.6.2.1
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting protobuf
  Using cached protobuf-3.14.0-cp38-cp38-manylinux1_x86_64.whl (1.0 MB)
Collecting flatbuffers
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Installing collected packages: numpy, six, typing-extensions, protobuf, onnx, flatbuffers, tflite
Successfully installed flatbuffers-1.12 numpy-1.19.5 onnx-1.8.0 protobuf-3.14.0 six-1.15.0 tflite-2.3.0 typing-extensions-3.7.4.3
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
(venv) paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ pip install wheel
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.36.2
(venv) paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ tflite2onnx/scripts/build-wheel.sh 
Requirement already satisfied: numpy in ./venv/lib/python3.8/site-packages (1.19.5)
Requirement already satisfied: onnx in ./venv/lib/python3.8/site-packages (1.8.0)
Requirement already satisfied: tflite in ./venv/lib/python3.8/site-packages (2.3.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./venv/lib/python3.8/site-packages (from onnx) (3.7.4.3)
Requirement already satisfied: protobuf in ./venv/lib/python3.8/site-packages (from onnx) (3.14.0)
Requirement already satisfied: six in ./venv/lib/python3.8/site-packages (from onnx) (1.15.0)
Requirement already satisfied: flatbuffers in ./venv/lib/python3.8/site-packages (from tflite) (1.12)
running bdist_wheel
running build
installing to /media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/tflite2onnx/assets/build
running install
running install_egg_info
running egg_info
creating tflite2onnx.egg-info
writing tflite2onnx.egg-info/PKG-INFO
writing dependency_links to tflite2onnx.egg-info/dependency_links.txt
writing entry points to tflite2onnx.egg-info/entry_points.txt
writing top-level names to tflite2onnx.egg-info/top_level.txt
writing manifest file 'tflite2onnx.egg-info/SOURCES.txt'
reading manifest file 'tflite2onnx.egg-info/SOURCES.txt'
writing manifest file 'tflite2onnx.egg-info/SOURCES.txt'
Copying tflite2onnx.egg-info to /media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/tflite2onnx/assets/build/tflite2onnx-0.3.1.egg-info
running install_scripts
creating /media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/tflite2onnx/assets/build/tflite2onnx-0.3.1.dist-info/WHEEL
creating '/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/tflite2onnx/assets/dist/tflite2onnx-0.3.1-py3-none-any.whl' and adding '/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/tflite2onnx/assets/build' to it
adding 'tflite2onnx-0.3.1.dist-info/METADATA'
adding 'tflite2onnx-0.3.1.dist-info/WHEEL'
adding 'tflite2onnx-0.3.1.dist-info/entry_points.txt'
adding 'tflite2onnx-0.3.1.dist-info/top_level.txt'
adding 'tflite2onnx-0.3.1.dist-info/RECORD'
removing /media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/tflite2onnx/assets/build
(venv) paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ pip install tflite2onnx/assets/
dist/  tests/ 
(venv) paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ pip install tflite2onnx/assets/dist/tflite2onnx-0.3.1-py3-none-any.whl 
Processing ./tflite2onnx/assets/dist/tflite2onnx-0.3.1-py3-none-any.whl
Installing collected packages: tflite2onnx
Successfully installed tflite2onnx-0.3.1
(venv) paulgavrikov@paulgavrikov-OMEN-by-HP-Laptop-15-dh1xxx:/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe$ tflite2onnx
Traceback (most recent call last):
  File "/media/paulgavrikov/DATA/noCNN/model_conversion/mediapipe/venv/bin/tflite2onnx", line 5, in <module>
    from tflite2onnx.convert import cmd_convert
ModuleNotFoundError: No module named 'tflite2onnx'
```

**Comment by jackwish** [comment]
Ok... So you can now build but the package seems not working. Could you upload the package so others can try it out?

**Comment by jackwish** [comment]
@paulgavrikov I notice that you are using `venv`. Sorry for confusing, but the _venv_ in my context is `virtualenv`. Could you try `virtualenv` (as it declares to be more powerful than `venv`...)?

**Comment by paulgavrikov** [comment]
@jackwish I had no idea venv and virtualenv were two different things! Anyway, I run into the same issue with virtualenv. Steps are similar to venv. Only difference is that I do not have to install wheel. 

Dist generated with virtualenv: https://github.com/paulgavrikov/tflite2onnx/blob/pr-newline-description/assets/dist/tflite2onnx-0.3.1-py3-none-any.whl

**Comment by jackwish** [comment]
@paulgavrikov Ok... I know what's going on here... We should have specified the package location in `setup.py` more decently, let me try to fix.

To workaround it, you can `cd tflite2onnx` before building the package.

**Comment by jackwish** [comment]
Building package in dir where `setup.py` or `setup.cfg` should the conversion of python. Maybe we don't need to make it possible to invoke the script in other directories. I have fixed the installation doc and that you for the patient of discussing this.

#59 is going to drop `setup.py` and switching to `setup.cfg` completely. We also schedule the dependency installation in our CI to further protect the initial building steps (without installing the development dependency described in `requirements.txt`). It will close this issue.

Thank you very much for reporting this issue @paulgavrikov @groncarolo !
