### ISSUE TITLE
Installation via pip git clone fails

### ISSUE THREAD

**Issue by paulgavrikov** [jackwish/tflite2onnx#50]
**Describe the bug**
It is not possible to install tflite2onnx via `pip install git+<REPO>` due to `AttributeError: module 'tflite.TensorType' has no attribute 'BOOL'
`

**To Reproduce**

```bash
pip3 install git+https://github.com/jackwish/tflite2onnx.git
Collecting git+https://github.com/jackwish/tflite2onnx.git
  Cloning https://github.com/jackwish/tflite2onnx.git to /tmp/pip-req-build-zjsf07kd
  Running command git clone -q https://github.com/jackwish/tflite2onnx.git /tmp/pip-req-build-zjsf07kd
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zjsf07kd/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zjsf07kd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-zjsf07kd/pip-egg-info
         cwd: /tmp/pip-req-build-zjsf07kd/
    Complete output (17 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zjsf07kd/setup.py", line 2, in <module>
        import tflite2onnx
      File "/tmp/pip-req-build-zjsf07kd/tflite2onnx/__init__.py", line 3, in <module>
        from tflite2onnx.convert import convert
      File "/tmp/pip-req-build-zjsf07kd/tflite2onnx/convert.py", line 7, in <module>
        from tflite2onnx.model import Model
      File "/tmp/pip-req-build-zjsf07kd/tflite2onnx/model.py", line 7, in <module>
        from tflite2onnx.graph import Graph
      File "/tmp/pip-req-build-zjsf07kd/tflite2onnx/graph.py", line 6, in <module>
        from tflite2onnx.tensor import TensorFactory
      File "/tmp/pip-req-build-zjsf07kd/tflite2onnx/tensor.py", line 7, in <module>
        from tflite2onnx import mapping
      File "/tmp/pip-req-build-zjsf07kd/tflite2onnx/mapping.py", line 35, in <module>
        TensorType.BOOL: 'bool',
    AttributeError: module 'tflite.TensorType' has no attribute 'BOOL'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Version**
Which version are you using? `master`.

**Additional context**
Ubuntu 20.04, python3.8.6

**Comment by jackwish** [comment]
Hi @paulgavrikov thanks for reporting this issue. We don't support direct install via pip due to the limitation of setuptools - package info distributed in setup.py and setup.cfg. Please follow the guide of the README. Thanks!

I am going to close this issue as it is a tool issue. Please reopen if any consideration.
